name: warble
description: An audio player for the go-flutter desktop engine, built on the beep library.
version: 0.0.2-dev.1
repository: https://github.com/jslater89/warble

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  path_provider: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        default_package: warble
      macos:
        default_package: warble
      linux:
        default_package: warble