name: warble
description: An audio-playing plugin for the go-flutter desktop embedding engine.
version: 0.1.0
repository: https://github.com/jslater89/warble

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  path_provider: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        default_package: warble
      macos:
        default_package: warble
      linux:
        default_package: warble